GET http://localhost:8080/welcome
Authorization: Basic bWF4OmR1bW15
###
GET http://localhost:8080/welcome/max
Authorization: Basic bWF4OmR1bW15
###
GET http://localhost:8080/users/max/todos
Authorization: Basic bWF4OmR1bW15
###
DELETE http://localhost:8080/users/max/todos/4
Authorization: Basic bWF4OmR1bW15
###
DELETE http://localhost:8080/users/max/todos/3
Authorization: Basic bWF4OmR1bW15
###
GET http://localhost:8080/users/max/todos/2
Authorization: Basic bWF4OmR1bW15
###
GET http://localhost:8080/users/max/todos/10
Authorization: Basic bWF4OmR1bW15
###
POST http://localhost:8080/users/max/todos
Authorization: Basic bWF4OmR1bW15
content-type: application/json

{
    "description": "Learn Spring Boot",
    "targetDate": "2021-05-30",
    "done": false
}
###
PUT http://localhost:8080/users/max/todos/3
Authorization: Basic bWF4OmR1bW15
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}
###
PUT http://localhost:8080/users/max/todos/10
Authorization: Basic bWF4OmR1bW15
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}