GET http://localhost:8080/welcome
###
GET http://localhost:8080/welcome/max
###
GET http://localhost:8080/users/max/todos
Authorization: Basic dXNlcjpjYTU1YTQ4NC05NjkzLTRjMWItOWEwZS03MzlkMWZlZjBmMWE=
###
DELETE http://localhost:8080/users/max/todos/4
###
DELETE http://localhost:8080/users/max/todos/3
###
GET http://localhost:8080/users/max/todos/2
###
GET http://localhost:8080/users/max/todos/10
###
POST http://localhost:8080/users/max/todos
content-type: application/json

{
    "description": "Learn Spring Boot",
    "targetDate": "2021-05-30",
    "done": false
}
###
PUT http://localhost:8080/users/max/todos/3
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}
###
PUT http://localhost:8080/users/max/todos/10
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}