
POST http://localhost:8080/authenticate
Origin: http://localhost:4200
content-type: application/json

{
    "username": "max",
    "password": "dummy"
}
###
GET http://localhost:8080/refresh
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
GET http://localhost:8080/welcome/max
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
GET http://localhost:8080/users/max/todos
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
DELETE http://localhost:8080/users/max/todos/4
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
DELETE http://localhost:8080/users/max/todos/3
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
GET http://localhost:8080/users/max/todos/2
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
GET http://localhost:8080/users/max/todos/10
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
###
POST http://localhost:8080/users/max/todos
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
content-type: application/json

{
    "description": "Learn Spring Boot",
    "targetDate": "2021-05-30",
    "done": false
}
###
PUT http://localhost:8080/users/max/todos/3
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}
###
PUT http://localhost:8080/users/max/todos/10
Origin: http://localhost:4200
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXgiLCJleHAiOjE2MTk4OTEzODgsImlhdCI6MTYxOTI4NjU4OH0.J12RLkvYAVpPSnpRc_WOBL0WjICh_zIAj82tNgU-jzRCnndjWeubzAEWCe8iJ8nxClSSd8CYHLqsuQr_Txf7tg
content-type: application/json

{
    "description": "Learn Reactive Programming",
    "targetDate": "2021-06-20",
    "done": true
}